"""Test the cameras."""
import pytest

from ..cameras import camera


def test_dummy_capture():
    """Test the shape of the image generated by the dummy camera."""
    shape = (120, 160, 3)
    test_memory = {}
    cam = camera.Camera(test_memory, camera_type="dummy", shape=shape)
    cam.update()
    assert test_memory["image"].shape == shape


def test_dummy_color():
    """Test the shape of the image generated by the dummy camera."""
    shape = (120, 160, 1)
    test_memory = {}
    cam = camera.Camera(test_memory, camera_type="dummy", shape=shape)
    cam.update()
    assert test_memory["image"].shape == shape


def test_replay_cam_error():
    shape = (120, 160, 1)
    test_memory = {}

    with pytest.raises(ValueError):
        camera.Camera(
            test_memory,
            camera_type="replay",
            shape=shape,
            dataset_path="this/is/a/fake/path",
        )
