// @ts-check
import Head from "next/head";
import Image from "next/image";
import io from "socket.io-client";
import { useEffect, useState } from "react";

export default function Home() {
  const [socket, setSocket] = useState(null);

  useEffect(() => {


    try{
      fetch("/api/socketio")
      .then(() => {
        const socket = io({
          transports: ["websocket"],
          reconnection: false,
        });
        setSocket(socket);

        socket.on("connect", () => {
          console.log("connect");
          socket.emit("send-msg");
        });

        socket.on("connect_failed", function () {
          console.log("Sorry, there seems to be an issue with the connection!");
        });

        socket.on("error", function () {
          console.log("Sorry, there seems to be an issue with the connection!");
        });

        socket.on("receive-msg", (data) => {
          console.log("data", data);
        });

        socket.on("ui-client-connected", () => {
          console.log("a user is connected");
        });

        socket.on("py-client-connected", () => {
          console.log("a car is connected");
        });

        socket.on("disconnect", () => {
          console.log("disconnect");
        });
      })
    }
    catch(e){
    }

  
  }, []);

  function handleClick(data) {
    if (socket) {
      socket.emit("send-msg", data);
    }
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>hello</h1>

      <button onClick={() => handleClick("test")}>click</button>
    </div>
  );
}
